//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public class VixDiskLibInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VixDiskLibInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VixDiskLibInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VixDiskLibInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VixDiskLibPINVOKE.delete_VixDiskLibInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VixDiskLibGeometry biosGeo {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_biosGeo_set(swigCPtr, VixDiskLibGeometry.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VixDiskLibPINVOKE.VixDiskLibInfo_biosGeo_get(swigCPtr);
      VixDiskLibGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new VixDiskLibGeometry(cPtr, false);
      return ret;
    } 
  }

  public VixDiskLibGeometry physGeo {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_physGeo_set(swigCPtr, VixDiskLibGeometry.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VixDiskLibPINVOKE.VixDiskLibInfo_physGeo_get(swigCPtr);
      VixDiskLibGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new VixDiskLibGeometry(cPtr, false);
      return ret;
    } 
  }

  public ulong capacity {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_capacity_set(swigCPtr, value);
    } 
    get {
      ulong ret = VixDiskLibPINVOKE.VixDiskLibInfo_capacity_get(swigCPtr);
      return ret;
    } 
  }

  public VixDiskLibAdapterType adapterType {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_adapterType_set(swigCPtr, (int)value);
    } 
    get {
      VixDiskLibAdapterType ret = (VixDiskLibAdapterType)VixDiskLibPINVOKE.VixDiskLibInfo_adapterType_get(swigCPtr);
      return ret;
    } 
  }

  public int numLinks {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_numLinks_set(swigCPtr, value);
    } 
    get {
      int ret = VixDiskLibPINVOKE.VixDiskLibInfo_numLinks_get(swigCPtr);
      return ret;
    } 
  }

  public string parentFileNameHint {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_parentFileNameHint_set(swigCPtr, value);
    } 
    get {
      string ret = VixDiskLibPINVOKE.VixDiskLibInfo_parentFileNameHint_get(swigCPtr);
      return ret;
    } 
  }

  public string uuid {
    set {
      VixDiskLibPINVOKE.VixDiskLibInfo_uuid_set(swigCPtr, value);
    } 
    get {
      string ret = VixDiskLibPINVOKE.VixDiskLibInfo_uuid_get(swigCPtr);
      return ret;
    } 
  }

  public VixDiskLibInfo() : this(VixDiskLibPINVOKE.new_VixDiskLibInfo(), true) {
  }

}

}
