//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public class VixDiskLibCreds : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VixDiskLibCreds(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VixDiskLibCreds obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VixDiskLibCreds() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VixDiskLibPINVOKE.delete_VixDiskLibCreds(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VixDiskLibUidPasswdCreds uid {
    set {
      VixDiskLibPINVOKE.VixDiskLibCreds_uid_set(swigCPtr, VixDiskLibUidPasswdCreds.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VixDiskLibPINVOKE.VixDiskLibCreds_uid_get(swigCPtr);
      VixDiskLibUidPasswdCreds ret = (cPtr == global::System.IntPtr.Zero) ? null : new VixDiskLibUidPasswdCreds(cPtr, false);
      return ret;
    } 
  }

  public VixDiskLibSessionIdCreds sessionId {
    set {
      VixDiskLibPINVOKE.VixDiskLibCreds_sessionId_set(swigCPtr, VixDiskLibSessionIdCreds.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VixDiskLibPINVOKE.VixDiskLibCreds_sessionId_get(swigCPtr);
      VixDiskLibSessionIdCreds ret = (cPtr == global::System.IntPtr.Zero) ? null : new VixDiskLibSessionIdCreds(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_VixDiskLibTicketIdCreds ticketId {
    set {
      VixDiskLibPINVOKE.VixDiskLibCreds_ticketId_set(swigCPtr, SWIGTYPE_p_VixDiskLibTicketIdCreds.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VixDiskLibPINVOKE.VixDiskLibCreds_ticketId_get(swigCPtr);
      SWIGTYPE_p_VixDiskLibTicketIdCreds ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_VixDiskLibTicketIdCreds(cPtr, false);
      return ret;
    } 
  }

  public VixDiskLibCreds() : this(VixDiskLibPINVOKE.new_VixDiskLibCreds(), true) {
  }

}

}
