//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public class VixDiskLibGeometry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VixDiskLibGeometry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VixDiskLibGeometry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VixDiskLibGeometry() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VixDiskLibPINVOKE.delete_VixDiskLibGeometry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint cylinders {
    set {
      VixDiskLibPINVOKE.VixDiskLibGeometry_cylinders_set(swigCPtr, value);
    } 
    get {
      uint ret = VixDiskLibPINVOKE.VixDiskLibGeometry_cylinders_get(swigCPtr);
      return ret;
    } 
  }

  public uint heads {
    set {
      VixDiskLibPINVOKE.VixDiskLibGeometry_heads_set(swigCPtr, value);
    } 
    get {
      uint ret = VixDiskLibPINVOKE.VixDiskLibGeometry_heads_get(swigCPtr);
      return ret;
    } 
  }

  public uint sectors {
    set {
      VixDiskLibPINVOKE.VixDiskLibGeometry_sectors_set(swigCPtr, value);
    } 
    get {
      uint ret = VixDiskLibPINVOKE.VixDiskLibGeometry_sectors_get(swigCPtr);
      return ret;
    } 
  }

  public VixDiskLibGeometry() : this(VixDiskLibPINVOKE.new_VixDiskLibGeometry(), true) {
  }

}

}
