//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public enum VixDiskLibDiskType {
  VIXDISKLIB_DISK_MONOLITHIC_SPARSE = 1,
  VIXDISKLIB_DISK_MONOLITHIC_FLAT = 2,
  VIXDISKLIB_DISK_SPLIT_SPARSE = 3,
  VIXDISKLIB_DISK_SPLIT_FLAT = 4,
  VIXDISKLIB_DISK_VMFS_FLAT = 5,
  VIXDISKLIB_DISK_STREAM_OPTIMIZED = 6,
  VIXDISKLIB_DISK_VMFS_THIN = 7,
  VIXDISKLIB_DISK_VMFS_SPARSE = 8,
  VIXDISKLIB_DISK_UNKNOWN = 256
}

}
