//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public class VixDiskLibUidPasswdCreds : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VixDiskLibUidPasswdCreds(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VixDiskLibUidPasswdCreds obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VixDiskLibUidPasswdCreds() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VixDiskLibPINVOKE.delete_VixDiskLibUidPasswdCreds(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string userName {
    set {
      VixDiskLibPINVOKE.VixDiskLibUidPasswdCreds_userName_set(swigCPtr, value);
    } 
    get {
      string ret = VixDiskLibPINVOKE.VixDiskLibUidPasswdCreds_userName_get(swigCPtr);
      return ret;
    } 
  }

  public string password {
    set {
      VixDiskLibPINVOKE.VixDiskLibUidPasswdCreds_password_set(swigCPtr, value);
    } 
    get {
      string ret = VixDiskLibPINVOKE.VixDiskLibUidPasswdCreds_password_get(swigCPtr);
      return ret;
    } 
  }

  public VixDiskLibUidPasswdCreds() : this(VixDiskLibPINVOKE.new_VixDiskLibUidPasswdCreds(), true) {
  }

}

}
