//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public enum VixDiskLibCredType {
  VIXDISKLIB_CRED_UID = 1,
  VIXDISKLIB_CRED_SESSIONID = 2,
  VIXDISKLIB_CRED_TICKETID = 3,
  VIXDISKLIB_CRED_SSPI = 4,
  VIXDISKLIB_CRED_UNKNOWN = 256
}

}
