//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backup.Services.VDDK {

public class VMRect : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VMRect(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VMRect obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VMRect() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VixDiskLibPINVOKE.delete_VMRect(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int left {
    set {
      VixDiskLibPINVOKE.VMRect_left_set(swigCPtr, value);
    } 
    get {
      int ret = VixDiskLibPINVOKE.VMRect_left_get(swigCPtr);
      return ret;
    } 
  }

  public int top {
    set {
      VixDiskLibPINVOKE.VMRect_top_set(swigCPtr, value);
    } 
    get {
      int ret = VixDiskLibPINVOKE.VMRect_top_get(swigCPtr);
      return ret;
    } 
  }

  public int right {
    set {
      VixDiskLibPINVOKE.VMRect_right_set(swigCPtr, value);
    } 
    get {
      int ret = VixDiskLibPINVOKE.VMRect_right_get(swigCPtr);
      return ret;
    } 
  }

  public int bottom {
    set {
      VixDiskLibPINVOKE.VMRect_bottom_set(swigCPtr, value);
    } 
    get {
      int ret = VixDiskLibPINVOKE.VMRect_bottom_get(swigCPtr);
      return ret;
    } 
  }

  public VMRect() : this(VixDiskLibPINVOKE.new_VMRect(), true) {
  }

}

}
