// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupItem_ItemType int32

const (
	BackupItem_FILE   BackupItem_ItemType = 0
	BackupItem_FOLDER BackupItem_ItemType = 1
)

// Enum value maps for BackupItem_ItemType.
var (
	BackupItem_ItemType_name = map[int32]string{
		0: "FILE",
		1: "FOLDER",
	}
	BackupItem_ItemType_value = map[string]int32{
		"FILE":   0,
		"FOLDER": 1,
	}
)

func (x BackupItem_ItemType) Enum() *BackupItem_ItemType {
	p := new(BackupItem_ItemType)
	*p = x
	return p
}

func (x BackupItem_ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupItem_ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (BackupItem_ItemType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x BackupItem_ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupItem_ItemType.Descriptor instead.
func (BackupItem_ItemType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4, 0}
}

// Request/Response for GetDrives
type GetDrivesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrivesRequest) Reset() {
	*x = GetDrivesRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrivesRequest) ProtoMessage() {}

func (x *GetDrivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrivesRequest.ProtoReflect.Descriptor instead.
func (*GetDrivesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GetDrivesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetDrivesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drives        []string               `protobuf:"bytes,1,rep,name=drives,proto3" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrivesResponse) Reset() {
	*x = GetDrivesResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrivesResponse) ProtoMessage() {}

func (x *GetDrivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrivesResponse.ProtoReflect.Descriptor instead.
func (*GetDrivesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetDrivesResponse) GetDrives() []string {
	if x != nil {
		return x.Drives
	}
	return nil
}

// Request/Response for GetContent
type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetContentRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type FolderContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []string               `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	Files         []string               `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderContent) Reset() {
	*x = FolderContent{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderContent) ProtoMessage() {}

func (x *FolderContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderContent.ProtoReflect.Descriptor instead.
func (*FolderContent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *FolderContent) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *FolderContent) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// Request/Response for Backup commands
type BackupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          BackupItem_ItemType    `protobuf:"varint,2,opt,name=type,proto3,enum=agentpb.BackupItem_ItemType" json:"type,omitempty"`
	LastWriteTime int64                  `protobuf:"varint,3,opt,name=last_write_time,json=lastWriteTime,proto3" json:"last_write_time,omitempty"` // Unix timestamp
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	StreamGuid    string                 `protobuf:"bytes,5,opt,name=stream_guid,json=streamGuid,proto3" json:"stream_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupItem) Reset() {
	*x = BackupItem{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupItem) ProtoMessage() {}

func (x *BackupItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupItem.ProtoReflect.Descriptor instead.
func (*BackupItem) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *BackupItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupItem) GetType() BackupItem_ItemType {
	if x != nil {
		return x.Type
	}
	return BackupItem_FILE
}

func (x *BackupItem) GetLastWriteTime() int64 {
	if x != nil {
		return x.LastWriteTime
	}
	return 0
}

func (x *BackupItem) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *BackupItem) GetStreamGuid() string {
	if x != nil {
		return x.StreamGuid
	}
	return ""
}

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	BackupId      string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *BackupRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

type BackupCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCompleteRequest) Reset() {
	*x = BackupCompleteRequest{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCompleteRequest) ProtoMessage() {}

func (x *BackupCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCompleteRequest.ProtoReflect.Descriptor instead.
func (*BackupCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *BackupCompleteRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

type BackupCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCompleteResponse) Reset() {
	*x = BackupCompleteResponse{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCompleteResponse) ProtoMessage() {}

func (x *BackupCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCompleteResponse.ProtoReflect.Descriptor instead.
func (*BackupCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

// Stream Service
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\aagentpb\"/\n" +
	"\x10GetDrivesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"+\n" +
	"\x11GetDrivesResponse\x12\x16\n" +
	"\x06drives\x18\x01 \x03(\tR\x06drives\"H\n" +
	"\x11GetContentRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\"?\n" +
	"\rFolderContent\x12\x18\n" +
	"\afolders\x18\x01 \x03(\tR\afolders\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\"\xd5\x01\n" +
	"\n" +
	"BackupItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.agentpb.BackupItem.ItemTypeR\x04type\x12&\n" +
	"\x0flast_write_time\x18\x03 \x01(\x03R\rlastWriteTime\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\x12\x1f\n" +
	"\vstream_guid\x18\x05 \x01(\tR\n" +
	"streamGuid\" \n" +
	"\bItemType\x12\b\n" +
	"\x04FILE\x10\x00\x12\n" +
	"\n" +
	"\x06FOLDER\x10\x01\"B\n" +
	"\rBackupRequest\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\"\x10\n" +
	"\x0eBackupResponse\"4\n" +
	"\x15BackupCompleteRequest\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\"\x18\n" +
	"\x16BackupCompleteResponse\",\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"!\n" +
	"\vStreamChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xdf\x02\n" +
	"\fAgentService\x12B\n" +
	"\tGetDrives\x12\x19.agentpb.GetDrivesRequest\x1a\x1a.agentpb.GetDrivesResponse\x12@\n" +
	"\n" +
	"GetContent\x12\x1a.agentpb.GetContentRequest\x1a\x16.agentpb.FolderContent\x129\n" +
	"\x06Backup\x12\x16.agentpb.BackupRequest\x1a\x17.agentpb.BackupResponse\x12Q\n" +
	"\x0eBackupComplete\x12\x1e.agentpb.BackupCompleteRequest\x1a\x1f.agentpb.BackupCompleteResponse\x12;\n" +
	"\tGetStream\x12\x16.agentpb.StreamRequest\x1a\x14.agentpb.StreamChunk0\x01B\x14Z\x12backup/pkg/agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_agent_proto_goTypes = []any{
	(BackupItem_ItemType)(0),       // 0: agentpb.BackupItem.ItemType
	(*GetDrivesRequest)(nil),       // 1: agentpb.GetDrivesRequest
	(*GetDrivesResponse)(nil),      // 2: agentpb.GetDrivesResponse
	(*GetContentRequest)(nil),      // 3: agentpb.GetContentRequest
	(*FolderContent)(nil),          // 4: agentpb.FolderContent
	(*BackupItem)(nil),             // 5: agentpb.BackupItem
	(*BackupRequest)(nil),          // 6: agentpb.BackupRequest
	(*BackupResponse)(nil),         // 7: agentpb.BackupResponse
	(*BackupCompleteRequest)(nil),  // 8: agentpb.BackupCompleteRequest
	(*BackupCompleteResponse)(nil), // 9: agentpb.BackupCompleteResponse
	(*StreamRequest)(nil),          // 10: agentpb.StreamRequest
	(*StreamChunk)(nil),            // 11: agentpb.StreamChunk
}
var file_proto_agent_proto_depIdxs = []int32{
	0,  // 0: agentpb.BackupItem.type:type_name -> agentpb.BackupItem.ItemType
	1,  // 1: agentpb.AgentService.GetDrives:input_type -> agentpb.GetDrivesRequest
	3,  // 2: agentpb.AgentService.GetContent:input_type -> agentpb.GetContentRequest
	6,  // 3: agentpb.AgentService.Backup:input_type -> agentpb.BackupRequest
	8,  // 4: agentpb.AgentService.BackupComplete:input_type -> agentpb.BackupCompleteRequest
	10, // 5: agentpb.AgentService.GetStream:input_type -> agentpb.StreamRequest
	2,  // 6: agentpb.AgentService.GetDrives:output_type -> agentpb.GetDrivesResponse
	4,  // 7: agentpb.AgentService.GetContent:output_type -> agentpb.FolderContent
	7,  // 8: agentpb.AgentService.Backup:output_type -> agentpb.BackupResponse
	9,  // 9: agentpb.AgentService.BackupComplete:output_type -> agentpb.BackupCompleteResponse
	11, // 10: agentpb.AgentService.GetStream:output_type -> agentpb.StreamChunk
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
